[package]
name = "mrz-core"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.7.16"

[features]
default = ["std"]
std = []

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
