[package]
name = "mrz-host"
version = "0.1.0"
edition = "2021"

[dependencies]
mrz-core = { path = "../mrz-core", features = ["std"] }
time = { version = "0.3", features = ["macros"] }

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
